### ISSUE TITLE
figure 1 not displayed with firefox browser

### ISSUE THREAD

**Issue by theo258** [Bertbk/course_gmsh#3]
Figure 1 in the [tutorial ](https://bthierry.pages.math.cnrs.fr/tutorial/gmsh/)is not displayed in my firefox browser version 75.0.

![no-pic](https://user-images.githubusercontent.com/60721219/80922329-2e6c8800-8d31-11ea-8087-53df62b5a39f.jpg)

**Comment by Bertbk** [comment]
Thanks for the report! I just fixed it. I also moved every image (`gif`, `jpg`, `png`, `svg`) to a specific folder (`img/`).
